### ISSUE TITLE
Cards stacking vertically

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/stack-in-card#2]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Don't know
**Last working release (if known):**

**Browser and Operating System:**
Macos Catalina with Safari or Brave

**Description of problem:**
Separate cards are stacked vertically if stack-in-card is used.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Garage, Pool & Lights are 3 separate vertical stacks.

The first screenshot shows the frontend with the standard vertical-stack card.  
The second screenshot shows the frontend when using custom:stack-in-card.

![Screenshot 2020-03-27 at 23 38 46](https://user-images.githubusercontent.com/34303331/77806948-8951f600-7086-11ea-9147-f30dc4230a22.png)
![Screenshot 2020-03-27 at 23 40 22](https://user-images.githubusercontent.com/34303331/77806953-8a832300-7086-11ea-96a4-0fbe36ff0848.png)

!

**Comment by schteff** [comment]
It seems to be because of this https://github.com/home-assistant/frontend/issues/5321

**Comment by McGiverGim** [comment]
I've observed the same in my case, but more exaggerated:

This is with vertical-stack:
![image](https://user-images.githubusercontent.com/2673520/78116460-9c592300-7404-11ea-9b17-9c2fcab79c53.png)

This is with stack-in-card (all the cards in a single column):
![image](https://user-images.githubusercontent.com/2673520/78116527-b8f55b00-7404-11ea-8f78-f21b79186aff.png)

The most curious is that if I press F5 to refresh the page...:
![image](https://user-images.githubusercontent.com/2673520/78116594-d62a2980-7404-11ea-89d9-9eb58f3f4ad6.png)

It seems to work as expected.

I suppose we need to wait until the bug is fixed to see if it is the culprit...

**Comment by PierreScerri** [comment]
That is a good observation.
I tried the refresh page trick on my Mac and it works too.
The link mentioned above (https://github.com/home-assistant/frontend/issues/5321) gives some indication of what the problem is.  It may also explain why refresh page works.

But, as you said, we will have to wait for a solution to be found.

**Comment by McGiverGim** [comment]
Is not only the F5 trick that works. If you copy the link and paste it into a browser, it works. Is only when you select the panel from the left menu when it does not work.

**Comment by PierreScerri** [comment]
This is the behaviour of the refresh page action:

[Screen Recording 2020-04-01 at 12.02.31.zip](https://github.com/custom-cards/stack-in-card/files/4414350/Screen.Recording.2020-04-01.at.12.02.31.zip)

**Comment by scstraus** [comment]
I'm also having this problem.

With vertical-stack-in card:

![image](https://user-images.githubusercontent.com/7644023/79504424-29ba8b00-8033-11ea-9501-e9ba8c4d37bc.png)


Without vertical-stack-in card:

![image](https://user-images.githubusercontent.com/7644023/79504078-89fcfd00-8032-11ea-8e37-176fb52a54fb.png)

**Comment by McGiverGim** [comment]
It seems the fix is almost ready: https://github.com/home-assistant/frontend/pull/6023

**Comment by tomlevels** [comment]
The issue is fixed in 0.111.0 and there is already a fix for vertical-stack-in-card, maybe this can help you:
https://github.com/ofekashery/vertical-stack-in-card/issues/80

**Comment by PierreScerri** [comment]
I'm on HA 0.111.7 and Stack-in-card 0.1.1 and the issue is still present

**Comment by scstraus** [comment]
How are you on .111.7 if it hasn't been released yet?

**Comment by PierreScerri** [comment]
My bad. It's 0.111.1.  I had just upgraded from 0.110.7

**Comment by scstraus** [comment]
Maybe stack-in card hasn't fixed it yet, you could try [vertical-stack-in-card](https://github.com/ofekashery/vertical-stack-in-card/issues/80), by all accounts, it's been fixed.

**Comment by tomlevels** [comment]
What I meant is that the bug in Home Assistant is fixed, now this custom card has to be fixed. For the vertical-stack-in-card, someone already proposed a pull-request for fixing this issue.

**Comment by scstraus** [comment]
It's not fixed in vertical-stack-in-card either.. Seems this one will be a problem for a while...

**Comment by PierreScerri** [comment]
I'm very sorry but I've given up on this card.
Removed it from my setup.

**Comment by redjab** [comment]
I created a fix for this if anyone wants to try: https://gist.github.com/redjab/283da2aab31af5dfd2e51549905dfe43.
It's probably a hack, haven't digged much into lovelace and how custom cards work, but this works fine in my setup

**Comment by scstraus** [comment]
I ended up moving to [Canary Card](https://github.com/jcwillox/lovelace-canary) which solves this problem for me (finally!).

**Comment by ildar170975** [comment]
Seems that the bug is still present.
It is erratic - sometimes cards have a proper layout, sometimes they are all stacked in one column.
Checked in Chrome.

**Comment by scstraus** [comment]
Yes, AFAIK no one has bothered fixing it, the only card that works is canary card.
